### ISSUE TITLE
RangeError: Invalid WebSocket frame: MASK must be clear

### ISSUE THREAD

**Issue by cjn566** [simap/Firestorm#4] opened 2020-08-12 01:53 UTC
I managed to get Firestorm up and running and got it to see my PB. I get the following message sequence in the terminal repeated about once per second. Also, whatever pattern is displaying will stutter at the times the message gets printed.

>connected to 192.168.0.31
sending to 1474969 at 192.168.0.31 {"getConfig":true,"listPrograms":true,"sendUpdates":false,"activeProgramId":"QF9srAAgnrnCAfLLv"}
RangeError: Invalid WebSocket frame: MASK must be clear
    at Receiver.getInfo (C:\Users\cjn56\Documents\Programming\Firestorm-master\node_modules\ws\lib\receiver.js:239:14)
    at Receiver.startLoop (C:\Users\cjn56\Documents\Programming\Firestorm-master\node_modules\ws\lib\receiver.js:131:22)
    at Receiver._write (C:\Users\cjn56\Documents\Programming\Firestorm-master\node_modules\ws\lib\receiver.js:78:10)
    at doWrite (_stream_writable.js:441:12)
    at writeOrBuffer (_stream_writable.js:425:5)
    at Receiver.Writable.write (_stream_writable.js:316:11)
    at Socket.socketOnData (C:\Users\cjn56\Documents\Programming\Firestorm-master\node_modules\ws\lib\websocket.js:872:35)
    at Socket.emit (events.js:311:20)
    at Socket.EventEmitter.emit (domain.js:482:12)
    at addChunk (_stream_readable.js:294:12) {
  [Symbol(status-code)]: 1002
}

Also, I'm not sure if it's expected behavior or not, but if I change the pattern through the PB's UI, rather than through firestorm, the pattern will revert back to the last pattern selected on firestorm.

**Comment by simap** [comment] 2020-09-18 17:52
I think this might be caused by the way PB handles preview data. Closing the browser window, or clicking on the live preview to disable it should allow Firestorm to connect without issue. It's a bug in PB though, in some code that tries to handle when a client goes away without closing the connection. 

Do you get this issue when no browser is connected to PB?

**Comment by simap** [comment] 2020-10-01 17:03
going to close for now - if it isn't that cause and you still see it, we can reopen

**Closed by simap** 2020-10-01 17:03 UTC
